/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.

solution: 4613732
*/

const ANSWER = 4613732;
const UPPER_BOUND = 4_000_000;

function main() {
  let total = 0;
  for (const fibNum of evenFibNum()) {
    if (fibNum > UPPER_BOUND) {
      return total;
    }
    total += fibNum;
  }
}

const result = main();
console.log('correct?', ANSWER === result);

function* genFib() {
  let a = 0;
  let b = 1;
  let num;
  while (true) {
    num = a + b;
    yield num;
    a = b;
    b = num;
  }
}

function* evenFibNum() {
  while (true) {
    for (const fibNum of genFib()) {
      if (isEven(fibNum)) {
        yield fibNum;
      }
    }
  }
}

function isEven(val: number) {
  return val % 2 === 0;
}
